### ISSUE TITLE
GKE SA is managed by GKE Project's SA, should we change this?

### ISSUE THREAD

**Issue by mathieu-benoit** [mathieu-benoit/acm-workshop#1]
Currently the GKE SA is managed by GKE Project's SA, should we change this?

Currently we do this:
```
## Org Admin

cat <<EOF > ~/$WORKSHOP_ORG_DIR_NAME/config-sync/projects/$GKE_PROJECT_ID/service-account-admin.yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: service-account-admin-${GKE_PROJECT_ID}
  namespace: config-control
spec:
  member: serviceAccount:${GKE_PROJECT_ID}@${CONFIG_CONTROLLER_PROJECT_ID}.iam.gserviceaccount.com
  role: roles/iam.serviceAccountAdmin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/${GKE_PROJECT_ID}
EOF
cat <<EOF > ~/$WORKSHOP_ORG_DIR_NAME/config-sync/projects/$GKE_PROJECT_ID/iam-admin.yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iam-admin-${GKE_PROJECT_ID}
  namespace: config-control
spec:
  member: serviceAccount:${GKE_PROJECT_ID}@${CONFIG_CONTROLLER_PROJECT_ID}.iam.gserviceaccount.com
  role: roles/resourcemanager.projectIamAdmin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/${GKE_PROJECT_ID}
EOF

## Platform Admin

cat <<EOF > ~/$GKE_PLATFORM_DIR_NAME/config-sync/gke-primary-pool-sa.yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: gke-primary-pool
  namespace: ${GKE_PROJECT_ID}
spec:
  displayName: gke-primary-pool
EOF

cat <<EOF > ~/$GKE_PLATFORM_DIR_NAME/config-sync/log-writer-gke-sa.yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: log-writer-gke
  namespace: ${GKE_PROJECT_ID}
spec:
  memberFrom:
    serviceAccountRef:
      name: gke-primary-pool
      namespace: ${GKE_PROJECT_ID}
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: ${GKE_PROJECT_ID}
  role: roles/logging.logWriter
EOF
```

In one hand, it's providing flexibility and autonomy for the Platform Admin, but on the other hand, the point is, on a security perspective, the Org Admin is giving too much power to the Platform Admin? The latter can create any Service Account and assign any IAM roles. To avoid this and restrict this, should we have the Org Admin creating these Service Account and IAM roles in `config-control` namespace? Not sure... but filing this note here to think more about that later.
