### ISSUE TITLE
`distroless` is not working

### ISSUE THREAD

**Issue by mathieu-benoit** [mathieu-benoit/acm-workshop#20]
With the current setup `distroless` for `istio-proxy` is not working as expected, need to debug this.

**Comment by mathieu-benoit** [comment]
This below is working:
```
apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      image:
        imageType: distroless
kind: ConfigMap
metadata:
  name: istio-${ASM_VERSION}
  namespace: istio-system
```

But not this:
```
apiVersion: v1
data:
  mesh: |-
    enableTracing: true
    defaultConfig:
      image:
        imageType: distroless
      tracing:
        stackdriver:{}
kind: ConfigMap
metadata:
  name: istio-${ASM_VERSION}
  namespace: istio-system
```
So filing this new issue for debugging/enabling Cloud Trace.

`distroless` is now fixed with the former yaml, closing this issue.
