### ISSUE TITLE
ASM - Cloud Tracing

### ISSUE THREAD

**Issue by mathieu-benoit** [mathieu-benoit/acm-workshop#24]
https://cloud.google.com/service-mesh/docs/managed/enable-managed-anthos-service-mesh-optional-features#enable_cloud_tracing

For some reasons, this below is not working as per #20, need to debug this further:
```
apiVersion: v1
data:
  mesh: |-
    enableTracing: true
    defaultConfig:
      image:
        imageType: distroless
      tracing:
        stackdriver:{}
kind: ConfigMap
metadata:
  name: istio-${ASM_VERSION}
  namespace: istio-system
```
